### ISSUE TITLE
GaoDe map get current location

### ISSUE THREAD

**Issue by cquezpro** [dji-sdk/Mobile-SDK-Doc#4]
Hello, Thanks for this git repo.
I'd like to know how to get current location using GaoDe map on the web site.(no mobile)

Thanks

**Comment by oliverou** [comment]
Hi @sirius2013 , I would suggest you to check it in GaoDe Map website: <http://lbs.amap.com>

**Comment by oliverou** [comment]
@sirius2013 , I will close this issue now. If you have any issues, please feel free to reopen it.
